matrix:
  include:
    - language: java
      sudo: false
      jdk: oraclejdk9
      script: mvn clean verify
      
    - language: node_js
      node_js:
        - "8.9.4"
      before_script:
       - cd src/main/resources/frontend/
       - npm install @angular/cli
      script:
        - ng build
        - ng test
      addons:
          chrome: stable
