matrix:
  include:
    - language: java
      sudo: false
      jdk: oraclejdk9
      script: mvn clean verify
      
    - language: node_js
      env:
        - DISPLAY=:99.0
      node_js:
        - "8.9.4"
      before_install:
        - sh -e /etc/init.d/xvfb start
      before_script:
       - cd src/main/resources/frontend/
       - npm install
      script:
        - ng build
        - ng test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
#          chrome: stable
